# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-11-03 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Accion', 'Accion'), ('Estreno', 'Estreno'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Anime', 'Anime'), ('Romance', 'Romance'), ('Documental', 'Documental'), ('Infantil', 'Infantil'), ('Drama', 'Drama')], max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('fondo', models.ImageField(upload_to='fondos')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ImageField(default='perfil/default.png', upload_to='perfil')),
                ('portada', models.ImageField(default='portada/default.png', upload_to='portada')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='valoraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('sinopsis', models.TextField(max_length=1200)),
                ('poster', models.ImageField(upload_to='posters')),
                ('url', models.CharField(max_length=800)),
                ('descarga', models.CharField(max_length=800)),
                ('trailer', models.CharField(max_length=800)),
                ('vistas', models.IntegerField(default=0)),
                ('favoritos', models.IntegerField(default=0)),
                ('valoracion', models.IntegerField(default=0)),
                ('fecha', models.CharField(max_length=40)),
                ('calidad', models.CharField(choices=[('HD', 'HD'), ('TSCREEN', 'TSCREEN'), ('DVDRIP', 'DVDRIP'), ('HDTS', 'HDTS')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='valoraciones',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.video'),
        ),
        migrations.AddField(
            model_name='slider',
            name='videopk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.video'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.video'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='videopk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.video'),
        ),
    ]
