# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_comentario_videopk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.usuario'),
        ),
    ]
