# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160308_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cont',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
