# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20160308_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='video_relacion',
            field=models.CharField(max_length=900),
        ),
    ]
