# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20160308_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='user_relacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='video_relacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ok',
            field=models.CharField(default='ok', max_length=200),
            preserve_default=False,
        ),
    ]
