# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20160308_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven', models.CharField(max_length=200)),
            ],
        ),
    ]
