# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20160308_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.video')),
            ],
        ),
    ]
