# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
