# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20160310_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='user_relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
