# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20160311_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ImageField(default='perfil/default.png', upload_to='perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='portada',
            field=models.ImageField(default='portada/default.png', upload_to='portada'),
        ),
    ]
