# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20160312_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descarga',
            field=models.CharField(default='ok', max_length=800),
            preserve_default=False,
        ),
    ]
