# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_video_descarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='video',
        ),
        migrations.DeleteModel(
            name='etiqueta',
        ),
    ]
