# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20160404_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='fondo',
        ),
    ]
