# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_remove_video_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='fondo',
            field=models.ImageField(default=datetime.datetime(2016, 4, 26, 21, 32, 31, 800726, tzinfo=utc), upload_to='fondos'),
            preserve_default=False,
        ),
    ]
