# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_video_vistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='vistas',
        ),
    ]
