# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_valoraciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
