# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_auto_20160508_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Accion', 'Accion'), ('Estreno', 'Estreno'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Anime', 'Anime'), ('Romance', 'Romance'), ('Documental', 'Documental'), ('Infantil', 'Infantil'), ('Drama', 'Drama')], default='Accion', max_length=122),
            preserve_default=False,
        ),
    ]
