# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_auto_20160508_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='calidad',
            field=models.CharField(choices=[('Accion', 'Accion'), ('Estreno', 'Estreno'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Anime', 'Anime'), ('Romance', 'Romance'), ('Documental', 'Documental'), ('Infantil', 'Infantil'), ('Drama', 'Drama')], default=datetime.datetime(2016, 5, 12, 0, 1, 11, 704479, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('HD', 'HD'), ('TSCREEN', 'TSCREEN'), ('DVDRIP', 'DVDRIP'), ('HDTS', 'HDTS')], max_length=122),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
