# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20160511_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Accion', 'Accion'), ('Estreno', 'Estreno'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Anime', 'Anime'), ('Romance', 'Romance'), ('Documental', 'Documental'), ('Infantil', 'Infantil'), ('Drama', 'Drama')], max_length=122),
        ),
        migrations.AlterField(
            model_name='video',
            name='calidad',
            field=models.CharField(choices=[('HD', 'HD'), ('TSCREEN', 'TSCREEN'), ('DVDRIP', 'DVDRIP'), ('HDTS', 'HDTS')], max_length=50),
        ),
    ]
