# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_remove_video_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='fecha',
            field=models.CharField(max_length=40),
        ),
    ]
